kind: Secret
apiVersion: v1
metadata:
  name: ssh-key
  namespace: debugging
type: Opaque
stringData:
  id_ed25519: |
    REPLACE_WITH_YOUR_PRIVATE_KEY_CONTENTS
  id_ed25519.pub: |
    REPLACE_WITH_YOUR_PUBLIC_KEY_CONTENTS