kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: debugging

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - bastion.yaml
  - ssh-tunnel.yaml
