kind: Secret
apiVersion: v1
metadata:
  name: postgresql-secret
  namespace: mlflow
type: Opaque
stringData:
  user: mlflow
  password: <postgresql-password>
  database: mlflow
---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow-s3-secret
  namespace: mlflow
type: Opaque
stringData:
  access-key: <aws-access-key-id>
  secret-key: <aws-secret-access-key>
  bucket-name: <s3-bucket-name>
  region: <aws-region>
---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow-ui-auth
  namespace: mlflow
type: Opaque
stringData:
  username: <mlflow-user>
  password: <mlflow-password>
  flask-seceret: <flask-secret-key>