apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mlflow
  namespace: mlflow
spec:
  parentRefs:
  - name: infra-gateway
    namespace: openshift-ingress
  hostnames:
  - "mlflow.infra.apps.REPLACE_ME"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: mlflow
      port: 5000
