namespace: openshift-marketplace
# Additional CatalogSources (required for pre-release OCP)
additionalCatalogSources:
  - name: rhoai-3-0
    namespace: openshift-marketplace
    image: REPLACE_ME
    displayName: Openshift AI 3.0
    publisher: Red Hat

# Operators to install
operators:
  - namespace: redhat-ods-operator
    channel: fast-3.x
    name: rhods-operator
    source: rhoai-3-0
    sourceNamespace: openshift-marketplace

imageDigestMirrorSets:
  - name: rhoai-registry-redhat-mirror-quay
    source: registry.redhat.io/rhoai
    mirrors:
      - quay.io/rhoai

consolePlugins: []