kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - task-load-generator.yaml
  - task-calculate-params-wva.yaml
  #- task-deploy-helmfile.yaml
  - task-sleep.yaml
  - task-verify-llm-d.yaml

namespace: pipelines