apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-lab
spec:
  destination:
    name: ''
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: envs/lab
    repoURL: https://github.com/aleskandro/llm-d-lab.git
    targetRevision: master
    kustomize:
       patches:
         # Patch to change repoURL for all Applications with the llm-d-lab label
         - target:
             kind: Application
             group: argoproj.io
             version: v1alpha1
             labelSelector: app.kubernetes.io/managed-by=llm-d-lab
           patch: |-
             - op: replace
               path: /spec/source/repoURL
               value: https://github.com/aleskandro/llm-d-lab.git
         - target:
             kind: Application
             group: argoproj.io
             version: v1alpha1
             name: infra-ocp-aws
           patch: |-
             - op: replace
               path: /spec/source/helm/valuesObject
               value:
                 # Retrieve the cluster-api-cluster value with:
                 # oc -n openshift-machine-api get machinesets -o jsonpath='{.items[0].metadata.labels.machine\.openshift\.io/cluster-api-cluster}{"\n"}'
                 clusterApiCluster: SET_ME
                 region: us-east-1
                 zones: ["a", "b", "c"]
                 amis: 
                   arm64: ami-08e3890b24e081680 
                   amd64: ami-01095d1967818437c
         - target:
             kind: Application
             group: argoproj.io
             version: v1alpha1
             name: gateway-api
           patch: |-
             - op: replace
               path: /spec/source/kustomize
               value:
                 patches:
                 - target:
                     group: gateway.networking.k8s.io
                     version: v1
                     kind: Gateway
                     name: openshift-ai-inference
                     namespace: openshift-ingress
                   patch: |-
                     - op: add
                       path: /spec/listeners/0/hostname
                       value: "inference-gateway.apps.SET_ME"
                 - target:
                     group: gateway.networking.k8s.io
                     version: v1
                     kind: Gateway
                     name: infra-gateway
                     namespace: openshift-ingress
                   patch: |-
                     - op: add
                       path: /spec/listeners/0/hostname
                       value: "infra-gateway.apps.SET_ME"
         - target:
             kind: Application
             group: argoproj.io
             version: v1alpha1
             name: loki-stack
           patch: |-
             - op: replace
               path: /spec/source/kustomize
               value:
                 patches:
                 - target:
                     group: loki.grafana.com
                     version: v1
                     kind: LokiStack
                     name: netobserv-loki
                   patch: |-
                     - op: replace
                       path: /spec/storageClassName
                       value: gp3-csi
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 10m0s
        factor: 2
