kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- namespace.yaml
- gitops-cluster-admin.yaml
- 99-loki-secret.yaml
- 99-grafana-credentials-secret.yaml
- 99-ssh-key-secret.yaml
- app-of-apps.yaml
