apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: infra-gateway
  namespace: openshift-ingress 
spec:
  gatewayClassName: openshift-default
  listeners:
  - name: http 
    port: 80
    protocol: HTTP
    #tls:
      #mode: Terminate
      #certificateRefs:
      #- name: REPLACE_ME
    allowedRoutes:
      namespaces:
        from: All