kind: Secret
apiVersion: v1
metadata:
  name: loki-s3
  namespace: netobserv   
stringData:
  access_key_id: <S3-like AWS access key id>
  access_key_secret: <S3-like AWS secret access key>
  bucketnames: <bucket name>
  endpoint: <endpoint>
  region: <region>